export const countryList = [
    { code: 'AF', code3: 'AFG', name: 'Afghanistan', number: '004' },
    { code: 'AL', code3: 'ALB', name: 'Albania', number: '008' },
    { code: 'DZ', code3: 'DZA', name: 'Algeria', number: '012' },
    { code: 'AS', code3: 'ASM', name: 'American Samoa', number: '016' },
    { code: 'AD', code3: 'AND', name: 'Andorra', number: '020' },
    { code: 'AO', code3: 'AGO', name: 'Angola', number: '024' },
    { code: 'AI', code3: 'AIA', name: 'Anguilla', number: '660' },
    { code: 'AQ', code3: 'ATA', name: 'Antarctica', number: '010' },
    { code: 'AG', code3: 'ATG', name: 'Antigua and Barbuda', number: '028' },
    { code: 'AR', code3: 'ARG', name: 'Argentina', number: '032' },
    { code: 'AM', code3: 'ARM', name: 'Armenia', number: '051' },
    { code: 'AW', code3: 'ABW', name: 'Aruba', number: '533' },
    { code: 'AU', code3: 'AUS', name: 'Australia', number: '036' },
    { code: 'AT', code3: 'AUT', name: 'Austria', number: '040' },
    { code: 'AZ', code3: 'AZE', name: 'Azerbaijan', number: '031' },
    { code: 'BS', code3: 'BHS', name: 'Bahamas (the)', number: '044' },
    { code: 'BH', code3: 'BHR', name: 'Bahrain', number: '048' },
    { code: 'BD', code3: 'BGD', name: 'Bangladesh', number: '050' },
    { code: 'BB', code3: 'BRB', name: 'Barbados', number: '052' },
    { code: 'BY', code3: 'BLR', name: 'Belarus', number: '112' },
    { code: 'BE', code3: 'BEL', name: 'Belgium', number: '056' },
    { code: 'BZ', code3: 'BLZ', name: 'Belize', number: '084' },
    { code: 'BJ', code3: 'BEN', name: 'Benin', number: '204' },
    { code: 'BM', code3: 'BMU', name: 'Bermuda', number: '060' },
    { code: 'BT', code3: 'BTN', name: 'Bhutan', number: '064' },
    { code: 'BO', code3: 'BOL', name: 'Bolivia (Plurinational State of)', number: '068' },
    { code: 'BQ', code3: 'BES', name: 'Bonaire, Sint Eustatius and Saba', number: '535' },
    { code: 'BA', code3: 'BIH', name: 'Bosnia and Herzegovina', number: '070' },
    { code: 'BW', code3: 'BWA', name: 'Botswana', number: '072' },
    { code: 'BV', code3: 'BVT', name: 'Bouvet Island', number: '074' },
    { code: 'BR', code3: 'BRA', name: 'Brazil', number: '076' },
    { code: 'IO', code3: 'IOT', name: 'British Indian Ocean Territory (the)', number: '086' },
    { code: 'BN', code3: 'BRN', name: 'Brunei Darussalam', number: '096' },
    { code: 'BG', code3: 'BGR', name: 'Bulgaria', number: '100' },
    { code: 'BF', code3: 'BFA', name: 'Burkina Faso', number: '854' },
    { code: 'BI', code3: 'BDI', name: 'Burundi', number: '108' },
    { code: 'CV', code3: 'CPV', name: 'Cabo Verde', number: '132' },
    { code: 'KH', code3: 'KHM', name: 'Cambodia', number: '116' },
    { code: 'CM', code3: 'CMR', name: 'Cameroon', number: '120' },
    { code: 'CA', code3: 'CAN', name: 'Canada', number: '124' },
    { code: 'KY', code3: 'CYM', name: 'Cayman Islands (the)', number: '136' },
    { code: 'CF', code3: 'CAF', name: 'Central African Republic (the)', number: '140' },
    { code: 'TD', code3: 'TCD', name: 'Chad', number: '148' },
    { code: 'CL', code3: 'CHL', name: 'Chile', number: '152' },
    { code: 'CN', code3: 'CHN', name: 'China', number: '156' },
    { code: 'CX', code3: 'CXR', name: 'Christmas Island', number: '162' },
    { code: 'CC', code3: 'CCK', name: 'Cocos (Keeling) Islands (the)', number: '166' },
    { code: 'CO', code3: 'COL', name: 'Colombia', number: '170' },
    { code: 'KM', code3: 'COM', name: 'Comoros (the)', number: '174' },
    { code: 'CD', code3: 'COD', name: 'Congo (the Democratic Republic of the)', number: '180' },
    { code: 'CG', code3: 'COG', name: 'Congo (the)', number: '178' },
    { code: 'CK', code3: 'COK', name: 'Cook Islands (the)', number: '184' },
    { code: 'CR', code3: 'CRI', name: 'Costa Rica', number: '188' },
    { code: 'HR', code3: 'HRV', name: 'Croatia', number: '191' },
    { code: 'CU', code3: 'CUB', name: 'Cuba', number: '192' },
    { code: 'CW', code3: 'CUW', name: 'Curaçao', number: '531' },
    { code: 'CY', code3: 'CYP', name: 'Cyprus', number: '196' },
    { code: 'CZ', code3: 'CZE', name: 'Czechia', number: '203' },
    { code: 'CI', code3: 'CIV', name: 'Côte d\'Ivoire', number: '384' },
    { code: 'DK', code3: 'DNK', name: 'Denmark', number: '208' },
    { code: 'DJ', code3: 'DJI', name: 'Djibouti', number: '262' },
    { code: 'DM', code3: 'DMA', name: 'Dominica', number: '212' },
    { code: 'DO', code3: 'DOM', name: 'Dominican Republic (the)', number: '214' },
    { code: 'EC', code3: 'ECU', name: 'Ecuador', number: '218' },
    { code: 'EG', code3: 'EGY', name: 'Egypt', number: '818' },
    { code: 'SV', code3: 'SLV', name: 'El Salvador', number: '222' },
    { code: 'GQ', code3: 'GNQ', name: 'Equatorial Guinea', number: '226' },
    { code: 'ER', code3: 'ERI', name: 'Eritrea', number: '232' },
    { code: 'EE', code3: 'EST', name: 'Estonia', number: '233' },
    { code: 'SZ', code3: 'SWZ', name: 'Eswatini', number: '748' },
    { code: 'ET', code3: 'ETH', name: 'Ethiopia', number: '231' },
    { code: 'FK', code3: 'FLK', name: 'Falkland Islands (the) [Malvinas]', number: '238' },
    { code: 'FO', code3: 'FRO', name: 'Faroe Islands (the)', number: '234' },
    { code: 'FJ', code3: 'FJI', name: 'Fiji', number: '242' },
    { code: 'FI', code3: 'FIN', name: 'Finland', number: '246' },
    { code: 'FR', code3: 'FRA', name: 'France', number: '250' },
    { code: 'GF', code3: 'GUF', name: 'French Guiana', number: '254' },
    { code: 'PF', code3: 'PYF', name: 'French Polynesia', number: '258' },
    { code: 'TF', code3: 'ATF', name: 'French Southern Territories (the)', number: '260' },
    { code: 'GA', code3: 'GAB', name: 'Gabon', number: '266' },
    { code: 'GM', code3: 'GMB', name: 'Gambia (the)', number: '270' },
    { code: 'GE', code3: 'GEO', name: 'Georgia', number: '268' },
    { code: 'DE', code3: 'DEU', name: 'Germany', number: '276' },
    { code: 'GH', code3: 'GHA', name: 'Ghana', number: '288' },
    { code: 'GI', code3: 'GIB', name: 'Gibraltar', number: '292' },
    { code: 'GR', code3: 'GRC', name: 'Greece', number: '300' },
    { code: 'GL', code3: 'GRL', name: 'Greenland', number: '304' },
    { code: 'GD', code3: 'GRD', name: 'Grenada', number: '308' },
    { code: 'GP', code3: 'GLP', name: 'Guadeloupe', number: '312' },
    { code: 'GU', code3: 'GUM', name: 'Guam', number: '316' },
    { code: 'GT', code3: 'GTM', name: 'Guatemala', number: '320' },
    { code: 'GG', code3: 'GGY', name: 'Guernsey', number: '831' },
    { code: 'GN', code3: 'GIN', name: 'Guinea', number: '324' },
    { code: 'GW', code3: 'GNB', name: 'Guinea-Bissau', number: '624' },
    { code: 'GY', code3: 'GUY', name: 'Guyana', number: '328' },
    { code: 'HT', code3: 'HTI', name: 'Haiti', number: '332' },
    { code: 'HM', code3: 'HMD', name: 'Heard Island and McDonald Islands', number: '334' },
    { code: 'VA', code3: 'VAT', name: 'Holy See (the)', number: '336' },
    { code: 'HN', code3: 'HND', name: 'Honduras', number: '340' },
    { code: 'HK', code3: 'HKG', name: 'Hong Kong', number: '344' },
    { code: 'HU', code3: 'HUN', name: 'Hungary', number: '348' },
    { code: 'IS', code3: 'ISL', name: 'Iceland', number: '352' },
    { code: 'IN', code3: 'IND', name: 'India', number: '356' },
    { code: 'ID', code3: 'IDN', name: 'Indonesia', number: '360' },
    { code: 'IR', code3: 'IRN', name: 'Iran (Islamic Republic of)', number: '364' },
    { code: 'IQ', code3: 'IRQ', name: 'Iraq', number: '368' },
    { code: 'IE', code3: 'IRL', name: 'Ireland', number: '372' },
    { code: 'IM', code3: 'IMN', name: 'Isle of Man', number: '833' },
    { code: 'IL', code3: 'ISR', name: 'Israel', number: '376' },
    { code: 'IT', code3: 'ITA', name: 'Italy', number: '380' },
    { code: 'JM', code3: 'JAM', name: 'Jamaica', number: '388' },
    { code: 'JP', code3: 'JPN', name: 'Japan', number: '392' },
    { code: 'JE', code3: 'JEY', name: 'Jersey', number: '832' },
    { code: 'JO', code3: 'JOR', name: 'Jordan', number: '400' },
    { code: 'KZ', code3: 'KAZ', name: 'Kazakhstan', number: '398' },
    { code: 'KE', code3: 'KEN', name: 'Kenya', number: '404' },
    { code: 'KI', code3: 'KIR', name: 'Kiribati', number: '296' },
    { code: 'KP', code3: 'PRK', name: 'Korea (the Democratic People\'s Republic of)', number: '408' },
    { code: 'KR', code3: 'KOR', name: 'Korea (the Republic of)', number: '410' },
    { code: 'KW', code3: 'KWT', name: 'Kuwait', number: '414' },
    { code: 'KG', code3: 'KGZ', name: 'Kyrgyzstan', number: '417' },
    { code: 'LA', code3: 'LAO', name: 'Lao People\'s Democratic Republic (the)', number: '418' },
    { code: 'LV', code3: 'LVA', name: 'Latvia', number: '428' },
    { code: 'LB', code3: 'LBN', name: 'Lebanon', number: '422' },
    { code: 'LS', code3: 'LSO', name: 'Lesotho', number: '426' },
    { code: 'LR', code3: 'LBR', name: 'Liberia', number: '430' },
    { code: 'LY', code3: 'LBY', name: 'Libya', number: '434' },
    { code: 'LI', code3: 'LIE', name: 'Liechtenstein', number: '438' },
    { code: 'LT', code3: 'LTU', name: 'Lithuania', number: '440' },
    { code: 'LU', code3: 'LUX', name: 'Luxembourg', number: '442' },
    { code: 'MO', code3: 'MAC', name: 'Macao', number: '446' },
    { code: 'MG', code3: 'MDG', name: 'Madagascar', number: '450' },
    { code: 'MW', code3: 'MWI', name: 'Malawi', number: '454' },
    { code: 'MY', code3: 'MYS', name: 'Malaysia', number: '458' },
    { code: 'MV', code3: 'MDV', name: 'Maldives', number: '462' },
    { code: 'ML', code3: 'MLI', name: 'Mali', number: '466' },
    { code: 'MT', code3: 'MLT', name: 'Malta', number: '470' },
    { code: 'MH', code3: 'MHL', name: 'Marshall Islands (the)', number: '584' },
    { code: 'MQ', code3: 'MTQ', name: 'Martinique', number: '474' },
    { code: 'MR', code3: 'MRT', name: 'Mauritania', number: '478' },
    { code: 'MU', code3: 'MUS', name: 'Mauritius', number: '480' },
    { code: 'YT', code3: 'MYT', name: 'Mayotte', number: '175' },
    { code: 'MX', code3: 'MEX', name: 'Mexico', number: '484' },
    { code: 'FM', code3: 'FSM', name: 'Micronesia (Federated States of)', number: '583' },
    { code: 'MD', code3: 'MDA', name: 'Moldova (the Republic of)', number: '498' },
    { code: 'MC', code3: 'MCO', name: 'Monaco', number: '492' },
    { code: 'MN', code3: 'MNG', name: 'Mongolia', number: '496' },
    { code: 'ME', code3: 'MNE', name: 'Montenegro', number: '499' },
    { code: 'MS', code3: 'MSR', name: 'Montserrat', number: '500' },
    { code: 'MA', code3: 'MAR', name: 'Morocco', number: '504' },
    { code: 'MZ', code3: 'MOZ', name: 'Mozambique', number: '508' },
    { code: 'MM', code3: 'MMR', name: 'Myanmar', number: '104' },
    { code: 'NA', code3: 'NAM', name: 'Namibia', number: '516' },
    { code: 'NR', code3: 'NRU', name: 'Nauru', number: '520' },
    { code: 'NP', code3: 'NPL', name: 'Nepal', number: '524' },
    { code: 'NL', code3: 'NLD', name: 'Netherlands (the)', number: '528' },
    { code: 'NC', code3: 'NCL', name: 'New Caledonia', number: '540' },
    { code: 'NZ', code3: 'NZL', name: 'New Zealand', number: '554' },
    { code: 'NI', code3: 'NIC', name: 'Nicaragua', number: '558' },
    { code: 'NE', code3: 'NER', name: 'Niger (the)', number: '562' },
    { code: 'NG', code3: 'NGA', name: 'Nigeria', number: '566' },
    { code: 'NU', code3: 'NIU', name: 'Niue', number: '570' },
    { code: 'NF', code3: 'NFK', name: 'Norfolk Island', number: '574' },
    { code: 'MP', code3: 'MNP', name: 'Northern Mariana Islands (the)', number: '580' },
    { code: 'NO', code3: 'NOR', name: 'Norway', number: '578' },
    { code: 'OM', code3: 'OMN', name: 'Oman', number: '512' },
    { code: 'PK', code3: 'PAK', name: 'Pakistan', number: '586' },
    { code: 'PW', code3: 'PLW', name: 'Palau', number: '585' },
    { code: 'PS', code3: 'PSE', name: 'Palestine, State of', number: '275' },
    { code: 'PA', code3: 'PAN', name: 'Panama', number: '591' },
    { code: 'PG', code3: 'PNG', name: 'Papua New Guinea', number: '598' },
    { code: 'PY', code3: 'PRY', name: 'Paraguay', number: '600' },
    { code: 'PE', code3: 'PER', name: 'Peru', number: '604' },
    { code: 'PH', code3: 'PHL', name: 'Philippines (the)', number: '608' },
    { code: 'PN', code3: 'PCN', name: 'Pitcairn', number: '612' },
    { code: 'PL', code3: 'POL', name: 'Poland', number: '616' },
    { code: 'PT', code3: 'PRT', name: 'Portugal', number: '620' },
    { code: 'PR', code3: 'PRI', name: 'Puerto Rico', number: '630' },
    { code: 'QA', code3: 'QAT', name: 'Qatar', number: '634' },
    { code: 'MK', code3: 'MKD', name: 'Republic of North Macedonia', number: '807' },
    { code: 'RO', code3: 'ROU', name: 'Romania', number: '642' },
    { code: 'RU', code3: 'RUS', name: 'Russian Federation (the)', number: '643' },
    { code: 'RW', code3: 'RWA', name: 'Rwanda', number: '646' },
    { code: 'RE', code3: 'REU', name: 'Réunion', number: '638' },
    { code: 'BL', code3: 'BLM', name: 'Saint Barthélemy', number: '652' },
    { code: 'SH', code3: 'SHN', name: 'Saint Helena, Ascension and Tristan da Cunha', number: '654' },
    { code: 'KN', code3: 'KNA', name: 'Saint Kitts and Nevis', number: '659' },
    { code: 'LC', code3: 'LCA', name: 'Saint Lucia', number: '662' },
    { code: 'MF', code3: 'MAF', name: 'Saint Martin (French part)', number: '663' },
    { code: 'PM', code3: 'SPM', name: 'Saint Pierre and Miquelon', number: '666' },
    { code: 'VC', code3: 'VCT', name: 'Saint Vincent and the Grenadines', number: '670' },
    { code: 'WS', code3: 'WSM', name: 'Samoa', number: '882' },
    { code: 'SM', code3: 'SMR', name: 'San Marino', number: '674' },
    { code: 'ST', code3: 'STP', name: 'Sao Tome and Principe', number: '678' },
    { code: 'SA', code3: 'SAU', name: 'Saudi Arabia', number: '682' },
    { code: 'SN', code3: 'SEN', name: 'Senegal', number: '686' },
    { code: 'RS', code3: 'SRB', name: 'Serbia', number: '688' },
    { code: 'SC', code3: 'SYC', name: 'Seychelles', number: '690' },
    { code: 'SL', code3: 'SLE', name: 'Sierra Leone', number: '694' },
    { code: 'SG', code3: 'SGP', name: 'Singapore', number: '702' },
    { code: 'SX', code3: 'SXM', name: 'Sint Maarten (Dutch part)', number: '534' },
    { code: 'SK', code3: 'SVK', name: 'Slovakia', number: '703' },
    { code: 'SI', code3: 'SVN', name: 'Slovenia', number: '705' },
    { code: 'SB', code3: 'SLB', name: 'Solomon Islands', number: '090' },
    { code: 'SO', code3: 'SOM', name: 'Somalia', number: '706' },
    { code: 'ZA', code3: 'ZAF', name: 'South Africa', number: '710' },
    { code: 'GS', code3: 'SGS', name: 'South Georgia and the South Sandwich Islands', number: '239' },
    { code: 'SS', code3: 'SSD', name: 'South Sudan', number: '728' },
    { code: 'ES', code3: 'ESP', name: 'Spain', number: '724' },
    { code: 'LK', code3: 'LKA', name: 'Sri Lanka', number: '144' },
    { code: 'SD', code3: 'SDN', name: 'Sudan (the)', number: '729' },
    { code: 'SR', code3: 'SUR', name: 'Suriname', number: '740' },
    { code: 'SJ', code3: 'SJM', name: 'Svalbard and Jan Mayen', number: '744' },
    { code: 'SE', code3: 'SWE', name: 'Sweden', number: '752' },
    { code: 'CH', code3: 'CHE', name: 'Switzerland', number: '756' },
    { code: 'SY', code3: 'SYR', name: 'Syrian Arab Republic', number: '760' },
    { code: 'TW', code3: 'TWN', name: 'Taiwan', number: '158' },
    { code: 'TJ', code3: 'TJK', name: 'Tajikistan', number: '762' },
    { code: 'TZ', code3: 'TZA', name: 'Tanzania, United Republic of', number: '834' },
    { code: 'TH', code3: 'THA', name: 'Thailand', number: '764' },
    { code: 'TL', code3: 'TLS', name: 'Timor-Leste', number: '626' },
    { code: 'TG', code3: 'TGO', name: 'Togo', number: '768' },
    { code: 'TK', code3: 'TKL', name: 'Tokelau', number: '772' },
    { code: 'TO', code3: 'TON', name: 'Tonga', number: '776' },
    { code: 'TT', code3: 'TTO', name: 'Trinidad and Tobago', number: '780' },
    { code: 'TN', code3: 'TUN', name: 'Tunisia', number: '788' },
    { code: 'TR', code3: 'TUR', name: 'Turkey', number: '792' },
    { code: 'TM', code3: 'TKM', name: 'Turkmenistan', number: '795' },
    { code: 'TC', code3: 'TCA', name: 'Turks and Caicos Islands (the)', number: '796' },
    { code: 'TV', code3: 'TUV', name: 'Tuvalu', number: '798' },
    { code: 'UG', code3: 'UGA', name: 'Uganda', number: '800' },
    { code: 'UA', code3: 'UKR', name: 'Ukraine', number: '804' },
    { code: 'AE', code3: 'ARE', name: 'United Arab Emirates (the)', number: '784' },
    { code: 'GB', code3: 'GBR', name: 'United Kingdom of Great Britain and Northern Ireland (the)', number: '826' },
    { code: 'UM', code3: 'UMI', name: 'United States Minor Outlying Islands (the)', number: '581' },
    { code: 'US', code3: 'USA', name: 'United States of America (the)', number: '840' },
    { code: 'UY', code3: 'URY', name: 'Uruguay', number: '858' },
    { code: 'UZ', code3: 'UZB', name: 'Uzbekistan', number: '860' },
    { code: 'VU', code3: 'VUT', name: 'Vanuatu', number: '548' },
    { code: 'VE', code3: 'VEN', name: 'Venezuela (Bolivarian Republic of)', number: '862' },
    { code: 'VN', code3: 'VNM', name: 'Viet Nam', number: '704' },
    { code: 'VG', code3: 'VGB', name: 'Virgin Islands (British)', number: '092' },
    { code: 'VI', code3: 'VIR', name: 'Virgin Islands (U.S.)', number: '850' },
    { code: 'WF', code3: 'WLF', name: 'Wallis and Futuna', number: '876' },
    { code: 'EH', code3: 'ESH', name: 'Western Sahara', number: '732' },
    { code: 'YE', code3: 'YEM', name: 'Yemen', number: '887' },
    { code: 'ZM', code3: 'ZMB', name: 'Zambia', number: '894' },
    { code: 'ZW', code3: 'ZWE', name: 'Zimbabwe', number: '716' },
    { code: 'AX', code3: 'ALA', name: 'Åland Islands', number: '248' }
];

export const timezoneList = [
    { name: '(GMT -12:00) Eniwetok, Kwajalein', value: '-12:00' },
    { name: '(GMT -11:00) Midway Island, Samoa', value: '-11:00' },
    { name: '(GMT -10:00) Hawaii', value: '-10:00' },
    { name: '(GMT -9:30) Taiohae', value: '-09:50' },
    { name: '(GMT -9:00) Alaska', value: '-09:00' },
    { name: '(GMT -8:00) Pacific Time (US, Canada)', value: '-08:00' },
    { name: '(GMT -7:00) Mountain Time (US, Canada)', value: '-07:00' },
    { name: '(GMT -6:00) Central Time (US, Canada), Mexico City', value: '-06:00' },
    { name: '(GMT -5:00) Eastern Time (US, Canada), Bogota, Lima', value: '-05:00' },
    { name: '(GMT -4:30) Caracas', value: '-04:50' },
    { name: '(GMT -4:00) Atlantic Time (Canada), Caracas, La Paz', value: '-04:00' },
    { name: '(GMT -3:30) Newfoundland', value: '-03:50' },
    { name: '(GMT -3:00) Brazil, Buenos Aires, Georgetown', value: '-03:00' },
    { name: '(GMT -2:00) Mid-Atlantic', value: '-02:00' },
    { name: '(GMT -1:00) Azores, Cape Verde Islands', value: '-01:00' },
    { name: '(GMT) Western Europe Time, London, Lisbon, Casablanca', value: '+00:00' },
    { name: '(GMT +1:00) Brussels, Copenhagen, Madrid, Paris', value: '+01:00' },
    { name: '(GMT +2:00) Kaliningrad, South Africa', value: '+02:00' },
    { name: '(GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg', value: '+03:00' },
    { name: '(GMT +3:30) Tehran', value: '+03:50' },
    { name: '(GMT +4:00) Abu Dhabi, Muscat, Baku, Tbilisi', value: '+04:00' },
    { name: '(GMT +4:30) Kabul', value: '+04:50' },
    { name: '(GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent', value: '+05:00' },
    { name: '(GMT +5:30) Bombay, Calcutta, Madras, New Delhi', value: '+05:50' },
    { name: '(GMT +5:45) Kathmandu, Pokhara', value: '+05:75' },
    { name: '(GMT +6:00) Almaty, Dhaka, Colombo', value: '+06:00' },
    { name: '(GMT +6:30) Yangon, Mandalay', value: '+06:50' },
    { name: '(GMT +7:00) Bangkok, Hanoi, Jakarta', value: '+07:00' },
    { name: '(GMT +8:00) Beijing, Perth, Singapore, Hong Kong', value: '+08:00' },
    { name: '(GMT +8:45) Eucla', value: '+08:75' },
    { name: '(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk', value: '+09:00' },
    { name: '(GMT +9:30) Adelaide, Darwin', value: '+09:50' },
    { name: '(GMT +10:00) Eastern Australia, Guam, Vladivostok', value: '+10:00' },
    { name: '(GMT +10:30) Lord Howe Island', value: '+10:50' },
    { name: '(GMT +11:00) Magadan, Solomon Islands, New Caledonia', value: '+11:00' },
    { name: '(GMT +11:30) Norfolk Island', value: '+11:50' },
    { name: '(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka', value: '+12:00' },
    { name: '(GMT +12:45) Chatham Islands', value: '+12:75' },
    { name: '(GMT +13:00) Apia, Nukualofa', value: '+13:00' },
    { name: '(GMT +14:00) Line Islands, Tokelau', value: '+14:00' }
];

export const phoneCodeList = [
    { value: '213', name: 'Algeria (+213)' },
    { value: '376', name: 'Andorra (+376)' },
    { value: '244', name: 'Angola (+244)' },
    { value: '1264', name: 'Anguilla (+1264)' },
    { value: '1268', name: 'Antigua, Barbuda (+1268)' },
    { value: '54', name: 'Argentina (+54)' },
    { value: '374', name: 'Armenia (+374)' },
    { value: '297', name: 'Aruba (+297)' },
    { value: '61', name: 'Australia (+61)' },
    { value: '43', name: 'Austria (+43)' },
    { value: '994', name: 'Azerbaijan (+994)' },
    { value: '1242', name: 'Bahamas (+1242)' },
    { value: '973', name: 'Bahrain (+973)' },
    { value: '880', name: 'Bangladesh (+880)' },
    { value: '1246', name: 'Barbados (+1246)' },
    { value: '375', name: 'Belarus (+375)' },
    { value: '32', name: 'Belgium (+32)' },
    { value: '501', name: 'Belize (+501)' },
    { value: '229', name: 'Benin (+229)' },
    { value: '1441', name: 'Bermuda (+1441)' },
    { value: '975', name: 'Bhutan (+975)' },
    { value: '591', name: 'Bolivia (+591)' },
    { value: '387', name: 'Bosnia Herzegovina (+387)' },
    { value: '267', name: 'Botswana (+267)' },
    { value: '55', name: 'Brazil (+55)' },
    { value: '673', name: 'Brunei (+673)' },
    { value: '359', name: 'Bulgaria (+359)' },
    { value: '226', name: 'Burkina Faso (+226)' },
    { value: '257', name: 'Burundi (+257)' },
    { value: '855', name: 'Cambodia (+855)' },
    { value: '237', name: 'Cameroon (+237)' },
    { value: '1', name: 'Canada (+1)' },
    { value: '238', name: 'Cape Verde Islands (+238)' },
    { value: '1345', name: 'Cayman Islands (+1345)' },
    { value: '236', name: 'Central African Republic (+236)' },
    { value: '56', name: 'Chile (+56)' },
    { value: '86', name: 'China (+86)' },
    { value: '57', name: 'Colombia (+57)' },
    { value: '269', name: 'Comoros (+269)' },
    { value: '242', name: 'Congo (+242)' },
    { value: '682', name: 'Cook Islands (+682)' },
    { value: '506', name: 'Costa Rica (+506)' },
    { value: '385', name: 'Croatia (+385)' },
    { value: '53', name: 'Cuba (+53)' },
    { value: '90392', name: 'Cyprus North (+90392)' },
    { value: '357', name: 'Cyprus South (+357)' },
    { value: '42', name: 'Czech Republic (+42)' },
    { value: '45', name: 'Denmark (+45)' },
    { value: '253', name: 'Djibouti (+253)' },
    { value: '1809', name: 'Dominica (+1809)' },
    { value: '1809', name: 'Dominican Republic (+1809)' },
    { value: '593', name: 'Ecuador (+593)' },
    { value: '20', name: 'Egypt (+20)' },
    { value: '503', name: 'El Salvador (+503)' },
    { value: '240', name: 'Equatorial Guinea (+240)' },
    { value: '291', name: 'Eritrea (+291)' },
    { value: '372', name: 'Estonia (+372)' },
    { value: '251', name: 'Ethiopia (+251)' },
    { value: '500', name: 'Falkland Islands (+500)' },
    { value: '298', name: 'Faroe Islands (+298)' },
    { value: '679', name: 'Fiji (+679)' },
    { value: '358', name: 'Finland (+358)' },
    { value: '33', name: 'France (+33)' },
    { value: '594', name: 'French Guiana (+594)' },
    { value: '689', name: 'French Polynesia (+689)' },
    { value: '241', name: 'Gabon (+241)' },
    { value: '220', name: 'Gambia (+220)' },
    { value: '7880', name: 'Georgia (+7880)' },
    { value: '49', name: 'Germany (+49)' },
    { value: '233', name: 'Ghana (+233)' },
    { value: '350', name: 'Gibraltar (+350)' },
    { value: '30', name: 'Greece (+30)' },
    { value: '299', name: 'Greenland (+299)' },
    { value: '1473', name: 'Grenada (+1473)' },
    { value: '590', name: 'Guadeloupe (+590)' },
    { value: '671', name: 'Guam (+671)' },
    { value: '502', name: 'Guatemala (+502)' },
    { value: '224', name: 'Guinea (+224)' },
    { value: '245', name: 'Guinea - Bissau (+245)' },
    { value: '592', name: 'Guyana (+592)' },
    { value: '509', name: 'Haiti (+509)' },
    { value: '504', name: 'Honduras (+504)' },
    { value: '852', name: 'Hong Kong (+852)' },
    { value: '36', name: 'Hungary (+36)' },
    { value: '354', name: 'Iceland (+354)' },
    { value: '91', name: 'India (+91)' },
    { value: '62', name: 'Indonesia (+62)' },
    { value: '98', name: 'Iran (+98)' },
    { value: '964', name: 'Iraq (+964)' },
    { value: '353', name: 'Ireland (+353)' },
    { value: '972', name: 'Israel (+972)' },
    { value: '39', name: 'Italy (+39)' },
    { value: '1876', name: 'Jamaica (+1876)' },
    { value: '81', name: 'Japan (+81)' },
    { value: '962', name: 'Jordan (+962)' },
    { value: '7', name: 'Kazakhstan (+7)' },
    { value: '254', name: 'Kenya (+254)' },
    { value: '686', name: 'Kiribati (+686)' },
    { value: '850', name: 'Korea North (+850)' },
    { value: '82', name: 'Korea South (+82)' },
    { value: '965', name: 'Kuwait (+965)' },
    { value: '996', name: 'Kyrgyzstan (+996)' },
    { value: '856', name: 'Laos (+856)' },
    { value: '371', name: 'Latvia (+371)' },
    { value: '961', name: 'Lebanon (+961)' },
    { value: '266', name: 'Lesotho (+266)' },
    { value: '231', name: 'Liberia (+231)' },
    { value: '218', name: 'Libya (+218)' },
    { value: '417', name: 'Liechtenstein (+417)' },
    { value: '370', name: 'Lithuania (+370)' },
    { value: '352', name: 'Luxembourg (+352)' },
    { value: '853', name: 'Macao (+853)' },
    { value: '389', name: 'Macedonia (+389)' },
    { value: '261', name: 'Madagascar (+261)' },
    { value: '265', name: 'Malawi (+265)' },
    { value: '60', name: 'Malaysia (+60)' },
    { value: '960', name: 'Maldives (+960)' },
    { value: '223', name: 'Mali (+223)' },
    { value: '356', name: 'Malta (+356)' },
    { value: '692', name: 'Marshall Islands (+692)' },
    { value: '596', name: 'Martinique (+596)' },
    { value: '222', name: 'Mauritania (+222)' },
    { value: '269', name: 'Mayotte (+269)' },
    { value: '52', name: 'Mexico (+52)' },
    { value: '691', name: 'Micronesia (+691)' },
    { value: '373', name: 'Moldova (+373)' },
    { value: '377', name: 'Monaco (+377)' },
    { value: '976', name: 'Mongolia (+976)' },
    { value: '1664', name: 'Montserrat (+1664)' },
    { value: '212', name: 'Morocco (+212)' },
    { value: '258', name: 'Mozambique (+258)' },
    { value: '95', name: 'Myanmar (+95)' },
    { value: '264', name: 'Namibia (+264)' },
    { value: '674', name: 'Nauru (+674)' },
    { value: '977', name: 'Nepal (+977)' },
    { value: '31', name: 'Netherlands (+31)' },
    { value: '687', name: 'New Caledonia (+687)' },
    { value: '64', name: 'New Zealand (+64)' },
    { value: '505', name: 'Nicaragua (+505)' },
    { value: '234', name: 'Nigeria (+234)' },
    { value: '227', name: 'Niger (+227)' },
    { value: '683', name: 'Niue (+683)' },
    { value: '672', name: 'Norfolk Islands (+672)' },
    { value: '670', name: 'Northern Marianas (+670)' },
    { value: '47', name: 'Norway (+47)' },
    { value: '968', name: 'Oman (+968)' },
    { value: '680', name: 'Palau (+680)' },
    { value: '507', name: 'Panama (+507)' },
    { value: '675', name: 'Papua New Guinea (+675)' },
    { value: '595', name: 'Paraguay (+595)' },
    { value: '51', name: 'Peru (+51)' },
    { value: '63', name: 'Philippines (+63)' },
    { value: '48', name: 'Poland (+48)' },
    { value: '351', name: 'Portugal (+351)' },
    { value: '1787', name: 'Puerto Rico (+1787)' },
    { value: '974', name: 'Qatar (+974)' },
    { value: '262', name: 'Reunion (+262)' },
    { value: '40', name: 'Romania (+40)' },
    { value: '7', name: 'Russia (+7)' },
    { value: '250', name: 'Rwanda (+250)' },
    { value: '378', name: 'San Marino (+378)' },
    { value: '239', name: 'Sao Tome, Principe (+239)' },
    { value: '966', name: 'Saudi Arabia (+966)' },
    { value: '221', name: 'Senegal (+221)' },
    { value: '381', name: 'Serbia (+381)' },
    { value: '248', name: 'Seychelles (+248)' },
    { value: '232', name: 'Sierra Leone (+232)' },
    { value: '65', name: 'Singapore (+65)' },
    { value: '421', name: 'Slovak Republic (+421)' },
    { value: '386', name: 'Slovenia (+386)' },
    { value: '677', name: 'Solomon Islands (+677)' },
    { value: '252', name: 'Somalia (+252)' },
    { value: '27', name: 'South Africa (+27)' },
    { value: '34', name: 'Spain (+34)' },
    { value: '94', name: 'Sri Lanka (+94)' },
    { value: '290', name: 'St. Helena (+290)' },
    { value: '1869', name: 'St. Kitts (+1869)' },
    { value: '1758', name: 'St. Lucia (+1758)' },
    { value: '249', name: 'Sudan (+249)' },
    { value: '597', name: 'Suriname (+597)' },
    { value: '268', name: 'Swaziland (+268)' },
    { value: '46', name: 'Sweden (+46)' },
    { value: '41', name: 'Switzerland (+41)' },
    { value: '963', name: 'Syria (+963)' },
    { value: '886', name: 'Taiwan (+886)' },
    { value: '7', name: 'Tajikstan (+7)' },
    { value: '66', name: 'Thailand (+66)' },
    { value: '228', name: 'Togo (+228)' },
    { value: '676', name: 'Tonga (+676)' },
    { value: '1868', name: 'Trinidad, Tobago (+1868)' },
    { value: '216', name: 'Tunisia (+216)' },
    { value: '90', name: 'Turkey (+90)' },
    { value: '7', name: 'Turkmenistan (+7)' },
    { value: '993', name: 'Turkmenistan (+993)' },
    { value: '1649', name: 'Turks, Caicos Islands (+1649)' },
    { value: '688', name: 'Tuvalu (+688)' },
    { value: '256', name: 'Uganda (+256)' },
    { value: '380', name: 'Ukraine (+380)' },
    { value: '971', name: 'United Arab Emirates (+971)' },
    { value: '598', name: 'Uruguay (+598)' },
    { value: '7', name: 'Uzbekistan (+7)' },
    { value: '678', name: 'Vanuatu (+678)' },
    { value: '379', name: 'Vatican City (+379)' },
    { value: '58', name: 'Venezuela (+58)' },
    { value: '84', name: 'Vietnam (+84)' },
    { value: '84', name: 'Virgin Islands - British (+1284)' },
    { value: '84', name: 'Virgin Islands - US (+1340)' },
    { value: '681', name: 'Wallis, Futuna (+681)' },
    { value: '969', name: 'Yemen (North)(+969)' },
    { value: '967', name: 'Yemen (South)(+967)' },
    { value: '260', name: 'Zambia (+260)' },
    { value: '263', name: 'Zimbabwe (+263)' }
];
